baseurl = "https://www.xavierbriole.com"
DefaultContentLanguage = "en"
theme = "hello-friend-ng"

PygmentsCodeFences = true
PygmentsStyle = "fruity"

googleAnalytics = "UA-127796557-1"

archetypeDir = "archetypes"
contentDir   = "content"
dataDir      = "data"
layoutDir    = "layouts"
publishDir   = "public"

buildDrafts  = false
buildFuture  = false
buildExpored = false
canonifyURLs = true

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  contentTypeName = "posts"
  defaultTheme = "light"
  themeColor = "#252627"

  customCSS = ["/css/custom.min.css"]
  customJS  = ["/js/script.min.js"]

  [[params.social]]
    name = "email"
    url  = "mailto:xbriole@icloud.com"

  [[params.social]]
    name = "facebook"
    url  = "https://www.facebook.com/xavierbriole"

  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/xavierbriole"

  [[params.social]]
    name = "instagram"
    url  = "https://www.instagram.com/xavierbriole"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/xavierbriole"

  [[params.social]]
    name = "github"
    url  = "https://github.com/xavierbriole"

  [[params.social]]
    name = "gitlab"
    url  = "https://gitlab.com/xavierbriole"

[languages]
  [languages.en]
    title = "Xavier Briole"
    subtitle = "Front-end Developer"
    homeSubtitle = "Front-end Developer"
    description = "Front-end Developer. This is my personal website with a small summary of me and some blog posts."
    keywords = "xavier, briole, web, front, end, developer, reactjs, react, javascript, js, css, html, php, native, marseille, aix, en, provence, france"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "$ cd /home/"
      logoHomeLink = "/"

    [languages.en.menu]
      # [[languages.en.menu.main]]
      #   identifier = "about"
      #   name = "About"
      #   url = "/about"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "stats"
        name = "Stats"
        url = "/stats"

[params.footer]
  trademark = true
  rss = false
  copyright = false
  author = false
  topText = ["Powered by <a href=\"http://gohugo.io\" target=\"_blank\">Hugo</a>"]

[permalinks]
  posts = "/posts/:year/:month/:title/"

[author]
  name = "Xavier Briole"

[blackfriday]
  hrefTargetBlank = true

[taxonomies]
  tag = "tags"
